language: python

python:
    - "3.7"
env:
  - SECRET_KEY='TEST' DB=sqlite3

# install requirements
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
    -  coverage run manage.py test && coverage report && coverage xml
after_success:
    - codecov
